name: HuntedDoubleChat
version: ${project.version}
main: me.lumboc.hunteddoublechat.HuntedDoubleChat
api-version: 1.16
authors: [ Lumboc ]
description: Creates a single MC chat for two different teams.
commands:
  hdctoggle:
    description: Toggle HDC
